(PDK-1275) changing to use the declared client
`instance.client` was causing the following error:

```
09:29:07 Failure/Error: require 'beaker-rspec'
09:29:07 NoMethodError:
09:29:07   undefined method `client' for #<Aws::EC2::Types::Instance:0x00000007099230>
```

As the client no longer appears to be a method of the `Instance` type. The return of `describe_instance_status` has also changed.